/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ToDoInterface extends utils.Interface {
  functions: {
    "ToDos(uint256)": FunctionFragment;
    "create(string,uint256,string)": FunctionFragment;
    "get(uint256)": FunctionFragment;
    "toggleCompleted(uint256)": FunctionFragment;
    "totalItemsInList()": FunctionFragment;
    "updateToDoItem(uint256,string)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "ToDos", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "create",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "get", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "toggleCompleted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalItemsInList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateToDoItem",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "ToDos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalItemsInList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateToDoItem",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ToDo extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ToDoInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ToDos(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, boolean] & {
        id: BigNumber;
        date: string;
        toDoItem: string;
        completed: boolean;
      }
    >;

    create(
      _text: string,
      _id: BigNumberish,
      _date: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    get(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, string, boolean]>;

    toggleCompleted(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalItemsInList(overrides?: CallOverrides): Promise<[BigNumber]>;

    updateToDoItem(
      _index: BigNumberish,
      _text: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  ToDos(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, boolean] & {
      id: BigNumber;
      date: string;
      toDoItem: string;
      completed: boolean;
    }
  >;

  create(
    _text: string,
    _id: BigNumberish,
    _date: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  get(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber, string, boolean]>;

  toggleCompleted(
    _index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalItemsInList(overrides?: CallOverrides): Promise<BigNumber>;

  updateToDoItem(
    _index: BigNumberish,
    _text: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ToDos(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, boolean] & {
        id: BigNumber;
        date: string;
        toDoItem: string;
        completed: boolean;
      }
    >;

    create(
      _text: string,
      _id: BigNumberish,
      _date: string,
      overrides?: CallOverrides
    ): Promise<void>;

    get(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, string, boolean]>;

    toggleCompleted(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    totalItemsInList(overrides?: CallOverrides): Promise<BigNumber>;

    updateToDoItem(
      _index: BigNumberish,
      _text: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    ToDos(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    create(
      _text: string,
      _id: BigNumberish,
      _date: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    get(_index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    toggleCompleted(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalItemsInList(overrides?: CallOverrides): Promise<BigNumber>;

    updateToDoItem(
      _index: BigNumberish,
      _text: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ToDos(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    create(
      _text: string,
      _id: BigNumberish,
      _date: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    get(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    toggleCompleted(
      _index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalItemsInList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateToDoItem(
      _index: BigNumberish,
      _text: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
